server:
  port: 8888
spring:
  application:
    name: erudio-config-server
#  Com o Spring cloud configurado, nao precisamos mais do profile
#  profiles:
#    active:
#    - native # Perfil do application.yml que estamos usando da aplicacao, nesse caso estamos usando o local, nao do Git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/5hapeshifter/erudio-config-server
          # Se fosse repositorio privado precisariamos informar os dados abaixo
          #username: ysername
          #password: password
          default-label: main #branch a ser acessada
          search-paths:
            - 'greeting-service*' #pasta onde estão os arquivos que devem ser acessados